AutoRental/Models/Return.cs
namespace AutoRental.Models
{
    using System;
    public partial class Return
    {
        public int IDReturn { get; set; }
        public string CarNo { get; set; }
        public Nullable<int> IDPerson { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> elsp { get; set; }
        public Nullable<int> fine { get; set; }
    }
}

AutoRental/Controllers/ReturnController.cs
using AutoRental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.SqlServer;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;

namespace AutoRental.Controllers
{
    public class ReturnController : Controller
    {
        AutoRentalDBEntities db = new AutoRentalDBEntities();
        // GET: Return
        public ActionResult Index()
        {
            return View(db.Returns.ToList());
        }
        public ActionResult Save(Return ret)
        {
            if (ModelState.IsValid)
            {
                db.Returns.Add(ret);
                var car = db.Cars.SingleOrDefault(e => e.CarNo == ret.CarNo);
                if(car == null)
                {
                    return HttpNotFound("404");
                }
                car.Status = "available";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ret);
        }
        [HttpPost]
        public ActionResult Getid(string carno)
        {
            var carn = (from s in db.Rentals join p in db.People on s.IDPerson equals p.IDPerson
                        where s.CarNo == carno
                        select new
                        { 
                            CarNo = s.CarNo,
                            IDPerson = s.IDPerson,
                            EndDate = s.EndDate,
                            Email = p.Email,
                            elsp = SqlFunctions.DateDiff("day", s.EndDate, DateTime.Now)
                        }).ToArray();
            return Json(carn,JsonRequestBehavior.AllowGet);
        }
    }
}

AutoRental/Views/Return/Index.cshtml
@model IEnumerable<AutoRental.Models.Return>
<div class="row">
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "Return", FormMethod.Post, new { id = "popupForm" }))
        {
            <div>
                <h2>Returns</h2>
            </div>

            <div>
                <div class="form-group">
                    <label class="form-label">CarNo</label>
                    <input type="text" id="carno" name="carno" class="form-control" placeholder="CarNo" required />
                </div>

                <div class="form-group">
                    <label class="form-label">IDPerson</label>
                    <input type="text" id="idperson" name="idperson" class="form-control" placeholder="IDPerson" required />
                </div>

                <div class="form-group">
                    <label class="form-label">Return Date</label>
                    <input type="text" id="returndate" name="returndate" class="form-control" placeholder="ReturnDate" required />
                </div>

                <div class="form-group">
                    <label class="form-label">elsp</label>
                    <input type="text" id="elsp" name="elsp" class="form-control" placeholder="elsp" required />
                </div>

                <div class="form-group">
                    <label class="form-label">fine</label>
                    <input type="text" id="fine" name="fine" class="form-control" placeholder="fine" required />
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
    <div class="col-sm-8">
        <table class="table">
            <tr>
                <th><center>CarNo</center></th>

                <th><center>Person</center></th>

                <th><center>ReturnDate</center></th>

                <th><center>Fine</center></th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td><center>@item.CarNo</center></td>
                    <td><center>@item.IDPerson</center></td>
                    <td><center>@item.ReturnDate</center></td>
                    @if (item.fine > 0)
                    {
                        <td style="background-color: lightcoral">
                            <center>
                                @item.fine
                            </center>
                        </td>
                    }
                </tr>
            }
        </table>

    </div>
    <div class="col-sm-12">
        <p id="myText"></p>
        <input type="text" id="email" name="email" placeholder="Email" required />
        <input type="button" onclick="sendMail()" value="Send" />
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script>
        getCarid();
        function getCarid() {
            $("#carno").keyup(function (e) {
                $.ajax({
                    type: 'POST',
                    url: '/Return/Getid?carno=' + $("#carno").val(),
                    dataType: 'JSON',
                    success: function (data)
                    {
                        console.log(data)
                        $('#idperson').val(data[data.length-1].IDPerson);
                        $('#returndate').val(new Date(parseInt(data[data.length-1].EndDate.substr(6))).toLocaleString());
                        $('#elsp').val(data[data.length - 1].elsp);
                        var elsp = data[data.length - 1].elsp;
                        if (elsp > 0)
                        {
                            var fine = elsp * 100;
                            $('#fine').val(fine.toString());
                        }
                        else
                        {
                            $('#fine').val("0");
                        }
                        $('#email').val(data[data.length - 1].Email);
                    }
                });
            });
        }
        function sendMail()
        {
            var adres = "mailto:"+document.getElementById("email").value.toString();
            var link = adres;
                + "?cc=myCCaddress@example.com"
                + "&subject=" + encodeURIComponent("Kara za przetrzymanie samochodu")
                + "&body=" + encodeURIComponent(document.getElementById('myText').value);
            window.location.href = link;
        }
    </script>
}