AutoRental/Models/Rental.cs
namespace AutoRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int IDRental { get; set; }
        public string CarNo { get; set; }
        public int IDPerson { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}

AutoRental/Models/RentalView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutoRental.Models
{
    public class RentalView
    {
        public int IDRental { get; set; }
        public string CarNo { get; set; }
        public int IDPerson { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
    }
}

AutoRental/Controllers/RentalController.cs
using AutoRental.Models;
using IronPdf;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoRental.Controllers
{
    public class RentalController : Controller
    {
        AutoRentalDBEntities db = new AutoRentalDBEntities();
        // GET: Rental
        public ActionResult Index()
        {
            var result = (from r in db.Rentals
                          join c in db.Cars on r.CarNo equals c.CarNo
                          join p in db.People on r.IDPerson equals p.IDPerson
                          select new RentalView
                          {
                              IDRental = r.IDRental,
                              CarNo = r.CarNo,
                              IDPerson = r.IDPerson,
                              Name = p.Name,
                              Surname = p.Surname,
                              Price = r.Price,
                              StartDate = r.StartDate,
                              EndDate = r.EndDate,
                              Status = c.Status
                          }).ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult GetCar()
        {
            var car = db.Cars.ToList();
            return Json(car, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Getid(int id)
        {
            var person = (from s in db.People where s.IDPerson == id select s.Name).ToList();
            return Json(person, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Getstatus(string carno)
        {
            var carstatus = (from s in db.Cars where s.CarNo == carno select s.Status).FirstOrDefault();
            return Json(carstatus, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Save(Rental rental)
        {
            if (ModelState.IsValid)
            {
                db.Rentals.Add(rental);
                var car = db.Cars.SingleOrDefault(e => e.CarNo == rental.CarNo);
                if (car == null)
                {
                    return HttpNotFound("404");
                }
                car.Status = "rental";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rental);
        }
        //[HttpPost]
        public ActionResult Download(int? id)
        {
            Rental rental = db.Rentals.Find(id);
            var renderer = new HtmlToPdf();
            string template = "<div style='font-size:30px;'><center><u>Umowa wynajmu samochodu</u></center></div>" +
                "               <div style='font-size:25px;'>Stronami niniejszej umowy są:" +
                "                <p style='font-size:23px;'>1." + rental.Name + "</p>" +
                "                <p style='font-size:23px;'>Nazywany dalej Wypożyczający</p>" +
                "                <p style='font-size:23px;'>2. ASP.NET project </p>" +
                "                <p style='font-size:23px;'>Nazywany dalej Pożyczający</p></div>" +
                "                <div><p style='font-size:23px;'>Przedmiotem umowy jest samochód o numerach: <b>" + rental.CarNo + "</b></p>" +
                "                <p style='font-size:23px;'>Udostępniony Wypożyczającemu w dniu: <b>" + rental.StartDate + "</b></p>" +
                "                <p style='font-size:23px;'>Za opłatą w wysokości: <b>" + rental.Price + " PLN </b> za każdy dzień.</p>" +
                "                <p style='font-size:23px;'>Umowa wygasa z dniem: <b>" + rental.EndDate + "</b></p></div>";
            string path = "C:/Document.pdf";
            var PDF = renderer.RenderHtmlAsPdf(template);
            PDF.SaveAs(path);
            var process = new Process();
            process.StartInfo.UseShellExecute = true;
            process.StartInfo.FileName = path;
            process.Start();
            return RedirectToAction("Index");
        }

    }
}

AutoRental/Views/Rental/Index.cshtml
@model IEnumerable<AutoRental.Models.RentalView>
<div class="row">
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "Rental", FormMethod.Post, new { id = "popupForm" }))
        {
            <div>
                <h2>Rentails</h2>
            </div>

            <div>
                <div class="form-group">
                    <label class="form-label">CarNo</label>
                    <select class="form-control" id="carno" name="carno" placeholder="CarNo" required>
                        <option>Select car</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-label">IDPerson</label>
                    <input type="text" id="idperson" name="idperson" class="form-control" placeholder="IDPerson" required />
                </div>

                <div class="form-group">
                    <label class="form-label">Name</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Name" required />
                </div>

                <div class="form-group">
                    <label class="form-label">Price for day</label>
                    <input type="text" id="price" name="price" class="form-control" placeholder="Price" required />
                </div>

                <div class="form-group">
                    <label class="form-label">Start Date</label>
                    <input type="date" id="startdate" name="startdate" class="form-control" placeholder="StartDate" required />
                </div>

                <div class="form-group">
                    <label class="form-label">End Date</label>
                    <input type="date" id="enddate" name="enddate" class="form-control" placeholder="EndDate" required />
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
    <div class="col-sm-8">
        <table class="table">
            <tr>
                <th><center>CarNo</center></th>

                <th><center>Name</center></th>

                <th><center>Surname</center></th>

                <th><center>Price per day</center></th>

                <th><center>Start date</center></th>

                <th><center>End date</center></th>

                <th><center>Status</center></th>
            </tr>

            @foreach(var item in Model)
            {
        <tr>
            <td><center>@item.CarNo</center></td>
            <td><center>@item.Name</center></td>
            <td><center>@item.Surname</center></td>
            <td><center>@item.Price</center></td>
            <td><center>@item.StartDate</center></td>
            <td><center>@item.EndDate</center></td>
            @if (item.Status == "available")
            {
                <td style="background-color: lightgreen">
                    <!--<center>@item.Status</center>-->
                </td>
            }
            else
            {
                <td style="background-color: lightcoral">
                    <!--<center>@item.Status</center>-->
                </td>
            }
            <td>
                @Html.ActionLink("Download", "Download", new { id = item.IDRental })
            </td>
        </tr>
            }
        </table>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        getCar();
        load();

        function load()
        {
            $("#idperson").attr("disabled", "disabled");
            $("#name").attr("disabled", "disabled");
            $("#price").attr("disabled", "disabled");
            $("#startdate").attr("disabled", "disabled");
            $("#enddate").attr("disabled", "disabled");
        }

        function getCar()
        {
            $.ajax({
                type: 'GET',
                url: '/Rental/GetCar',
                dataType: 'JSON',
                success: function (data)
                {
                    console.log(data);
                    for (var i = 0; i < data.length; i++)
                    {
                        $("#carno").append($("<option/>", {
                               text: data[i].CarNo
                        }));
                    }
                }
            });
        }
        $("#carno").change(function ()
        {
            status();
        });
        function status()
        {
            $.ajax({
                type: 'POST',
                url: '/Rental/Getstatus?carno=' + $("#carno").val(),
                dataType: 'JSON',
                success: function (data) {
                    console.log(data)
                    var status = data;
                    if (status == "available")
                    {
                        $("#idperson").removeAttr('disabled');
                        $("#name").removeAttr('disabled');
                        $("#price").removeAttr('disabled');
                        $("#startdate").removeAttr('disabled');
                        $("#enddate").removeAttr('disabled');
                    }
                    else
                    {
                        $("#idperson").attr("disabled", "disabled");
                        $("#name").attr("disabled", "disabled");
                        $("#price").attr("disabled", "disabled");
                        $("#startdate").attr("disabled", "disabled");
                        $("#enddate").attr("disabled", "disabled");
                    }
                }
            });
        }
        getCustomer();
        function getCustomer()
        {
            $("#idperson").keyup(function (e) {
                $.ajax({
                    type: 'POST',
                    url: '/Rental/Getid?id=' + $("#idperson").val(),
                    dataType: 'JSON',
                    success: function (data) {
                        console.log(data)
                        $("#name").val(data)
                    }
                });
            });
        }
    </script>
}